apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bge-m3
  namespace: kubeflow-user-example-com
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "s3://models/bge-m3/"